#!/bin/bash

if [[ -n ${EMPTY_BACKUP:-} ]]; then
	echo >&2 "nothing to backup; exiting without producing any output"
	echo >&2 "(EMPTY_BACKUP=${EMPTY_BACKUP})"
	exit 0
fi

for x in $(seq 1 42); do
	echo >&2 "synchronizing to backup block $x"
	echo "<< BLOCK $x >>"
	dd if=/dev/urandom bs=32 count=32 2>/dev/null | base64
	echo >&2 "wrote backup block $x... OK"
	echo
done

echo >&2 "backup blocks flushed"
exit 0
